// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD311MK3s7tvjXai6cjKgj9VeI0o7PQTO0',
    appId: '1:104803424957:web:251191279e1a6ca81135d4',
    messagingSenderId: '104803424957',
    projectId: 'ecommerceapp-34480',
    authDomain: 'ecommerceapp-34480.firebaseapp.com',
    storageBucket: 'ecommerceapp-34480.appspot.com',
    measurementId: 'G-FFNNWYY52T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADHfGhiORE14GPXC2WaXfLalUYr6rmr3g',
    appId: '1:104803424957:android:be11b10530c07a821135d4',
    messagingSenderId: '104803424957',
    projectId: 'ecommerceapp-34480',
    storageBucket: 'ecommerceapp-34480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNn7KOStAn8qxRh7fG7c5-4FVZcO-du8',
    appId: '1:104803424957:ios:82e694ae82dec2851135d4',
    messagingSenderId: '104803424957',
    projectId: 'ecommerceapp-34480',
    storageBucket: 'ecommerceapp-34480.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNn7KOStAn8qxRh7fG7c5-4FVZcO-du8',
    appId: '1:104803424957:ios:82e694ae82dec2851135d4',
    messagingSenderId: '104803424957',
    projectId: 'ecommerceapp-34480',
    storageBucket: 'ecommerceapp-34480.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD311MK3s7tvjXai6cjKgj9VeI0o7PQTO0',
    appId: '1:104803424957:web:c99117cdceb3c13d1135d4',
    messagingSenderId: '104803424957',
    projectId: 'ecommerceapp-34480',
    authDomain: 'ecommerceapp-34480.firebaseapp.com',
    storageBucket: 'ecommerceapp-34480.appspot.com',
    measurementId: 'G-JV7MS56Q33',
  );

}